export const CustomerService = {
    getData() {
        return [
            {
                id: 1000,
                marca: 'Chanel',
                perfume: 'Chanel No.5',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 100.43,
                preco_cartao: 100,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Chanel No.5 da marca Chanel, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 100,00 e no cartão de R$ 100,00',
            },
            {
                id: 1001,
                marca: 'Chanel',
                perfume: 'Chanel No.5',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 100,
                preco_cartao: 100,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Chanel No.5 da marca Chanel, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 100,00 e no cartão de R$ 100,00',
            },
            {
                id: 1002,
                marca: 'Dior',
                perfume: 'Sauvage',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 120,
                preco_cartao: 130,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Sauvage da marca Dior, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 120,00 e no cartão de R$ 130,00',
            },
            {
                id: 1003,
                marca: 'Versace',
                perfume: 'Bright Crystal',
                tamanho: 90,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 95,
                preco_cartao: 105,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Bright Crystal da marca Versace, tamanho 90, tipo EDT, genero Feminino, preço no pix de R$ 95,00 e no cartão de R$ 105,00',
            },
            {
                id: 1004,
                marca: 'Calvin Klein',
                perfume: 'Eternity',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 85,
                preco_cartao: 95,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Eternity da marca Calvin Klein, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 85,00 e no cartão de R$ 95,00',
            },
            {
                id: 1005,
                marca: 'Gucci',
                perfume: 'Guilty',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Masculino',
                preco_pix: 110,
                preco_cartao: 120,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Guilty da marca Gucci, tamanho 90, tipo EDP, genero Masculino, preço no pix de R$ 110,00 e no cartão de R$ 120,00',
            },
            {
                id: 1006,
                marca: 'Tom Ford',
                perfume: 'Black Orchid',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Unissex',
                preco_pix: 150,
                preco_cartao: 165,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Black Orchid da marca Tom Ford, tamanho 100, tipo EDP, genero Unissex, preço no pix de R$ 150,00 e no cartão de R$ 165,00',
            },
            {
                id: 1007,
                marca: 'Yves Saint Laurent',
                perfume: 'Black Opium',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Black Opium da marca Yves Saint Laurent, tamanho 90, tipo EDP, genero Feminino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1008,
                marca: 'Armani',
                perfume: 'Acqua di Gio',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Acqua di Gio da marca Armani, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1009,
                marca: 'Paco Rabanne',
                perfume: '1 Million',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume 1 Million da marca Paco Rabanne, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1010,
                marca: 'Marc Jacobs',
                perfume: 'Daisy',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 115,
                preco_cartao: 130,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Daisy da marca Marc Jacobs, tamanho 100, tipo EDT, genero Feminino, preço no pix de R$ 115,00 e no cartão de R$ 130,00',
            },
            {
                id: 1011,
                marca: 'Bvlgari',
                perfume: 'Man in Black',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Masculino',
                preco_pix: 135,
                preco_cartao: 150,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Man in Black da marca Bvlgari, tamanho 100, tipo EDP, genero Masculino, preço no pix de R$ 135,00 e no cartão de R$ 150,00',
            },
            {
                id: 1012,
                marca: 'Carolina Herrera',
                perfume: 'Good Girl',
                tamanho: 80,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Good Girl da marca Carolina Herrera, tamanho 80, tipo EDP, genero Feminino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1013,
                marca: 'Dolce & Gabbana',
                perfume: 'Light Blue',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Light Blue da marca Dolce & Gabbana, tamanho 100, tipo EDT, genero Feminino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1014,
                marca: 'Hermès',
                perfume: 'Terre d\'Hermès',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 160,
                preco_cartao: 175,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Terre d\'Hermès da marca Hermès, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 160,00 e no cartão de R$ 175,00',
            },
            {
                id: 1015,
                marca: 'Jimmy Choo',
                perfume: 'Man',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Man da marca Jimmy Choo, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1016,
                marca: 'Lancôme',
                perfume: 'La Vie Est Belle',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume La Vie Est Belle da marca Lancôme, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1017,
                marca: 'Montblanc',
                perfume: 'Legend',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 120,
                preco_cartao: 135,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Legend da marca Montblanc, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 120,00 e no cartão de R$ 135,00',
            },
            {
                id: 1018,
                marca: 'Narciso Rodriguez',
                perfume: 'For Her',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 150,
                preco_cartao: 165,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume For Her da marca Narciso Rodriguez, tamanho 90, tipo EDP, genero Feminino, preço no pix de R$ 150,00 e no cartão de R$ 165,00',
            },
            {
                id: 1019,
                marca: 'Prada',
                perfume: 'L\'Homme',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume L\'Homme da marca Prada, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1020,
                marca: 'Ralph Lauren',
                perfume: 'Polo Blue',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Polo Blue da marca Ralph Lauren, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1021,
                marca: 'Salvatore Ferragamo',
                perfume: 'Uomo',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Uomo da marca Salvatore Ferragamo, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1022,
                marca: 'Thierry Mugler',
                perfume: 'Alien',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 155,
                preco_cartao: 170,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Alien da marca Thierry Mugler, tamanho 90, tipo EDP, genero Feminino, preço no pix de R$ 155,00 e no cartão de R$ 170,00',
            },
            {
                id: 1023,
                marca: 'Valentino',
                perfume: 'Uomo',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Uomo da marca Valentino, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1024,
                marca: 'Viktor & Rolf',
                perfume: 'Flowerbomb',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 150,
                preco_cartao: 165,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Flowerbomb da marca Viktor & Rolf, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 150,00 e no cartão de R$ 165,00',
            },
            {
                id: 1025,
                marca: 'Zadig & Voltaire',
                perfume: 'This Is Her',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume This Is Her da marca Zadig & Voltaire, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1026,
                marca: 'Azzaro',
                perfume: 'Wanted',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 135,
                preco_cartao: 150,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Wanted da marca Azzaro, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 135,00 e no cartão de R$ 150,00',
            },
            {
                id: 1027,
                marca: 'Burberry',
                perfume: 'My Burberry',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume My Burberry da marca Burberry, tamanho 90, tipo EDP, genero Feminino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1028,
                marca: 'Cartier',
                perfume: 'La Panthère',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 160,
                preco_cartao: 175,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume La Panthère da marca Cartier, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 160,00 e no cartão de R$ 175,00',
            },
            {
                id: 1029,
                marca: 'Givenchy',
                perfume: 'Gentleman',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Masculino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Gentleman da marca Givenchy, tamanho 100, tipo EDP, genero Masculino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1030,
                marca: 'Hugo Boss',
                perfume: 'The Scent',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume The Scent da marca Hugo Boss, tamanho 100, tipo EDP, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1031,
                marca: 'Issey Miyake',
                perfume: 'L\'Eau d\'Issey',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 135,
                preco_cartao: 150,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume L\'Eau d\'Issey da marca Issey Miyake, tamanho 100, tipo EDT, genero Feminino, preço no pix de R$ 135,00 e no cartão de R$ 150,00',
            },
            {
                id: 1032,
                marca: 'Jean Paul Gaultier',
                perfume: 'Le Male',
                tamanho: 125,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Le Male da marca Jean Paul Gaultier, tamanho 125, tipo EDT, genero Masculino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1033,
                marca: 'Kenzo',
                perfume: 'Flower',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Flower da marca Kenzo, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1034,
                marca: 'Lacoste',
                perfume: 'L.12.12',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 120,
                preco_cartao: 135,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume L.12.12 da marca Lacoste, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 120,00 e no cartão de R$ 135,00',
            },
            {
                id: 1035,
                marca: 'Michael Kors',
                perfume: 'Wonderlust',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Wonderlust da marca Michael Kors, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1036,
                marca: 'Moschino',
                perfume: 'Toy Boy',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Masculino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Toy Boy da marca Moschino, tamanho 100, tipo EDP, genero Masculino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1037,
                marca: 'Nina Ricci',
                perfume: 'Luna',
                tamanho: 80,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Luna da marca Nina Ricci, tamanho 80, tipo EDP, genero Feminino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1038,
                marca: 'Paco Rabanne',
                perfume: 'Lady Million',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 135,
                preco_cartao: 150,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Lady Million da marca Paco Rabanne, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 135,00 e no cartão de R$ 150,00',
            },
            {
                id: 1039,
                marca: 'Roberto Cavalli',
                perfume: 'Paradiso',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Paradiso da marca Roberto Cavalli, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1040,
                marca: 'Salvatore Ferragamo',
                perfume: 'Signorina',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Signorina da marca Salvatore Ferragamo, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1041,
                marca: 'Tommy Hilfiger',
                perfume: 'Impact',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Impact da marca Tommy Hilfiger, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1042,
                marca: 'Versace',
                perfume: 'Eros',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Eros da marca Versace, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1043,
                marca: 'Yves Saint Laurent',
                perfume: 'Libre',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 150,
                preco_cartao: 165,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Libre da marca Yves Saint Laurent, tamanho 90, tipo EDP, genero Feminino, preço no pix de R$ 150,00 e no cartão de R$ 165,00',
            },
            {
                id: 1044,
                marca: 'Zara',
                perfume: 'Red Temptation',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 95,
                preco_cartao: 110,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Red Temptation da marca Zara, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 95,00 e no cartão de R$ 110,00',
            },
            {
                id: 1045,
                marca: 'Azzaro',
                perfume: 'Chrome',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 120,
                preco_cartao: 135,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Chrome da marca Azzaro, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 120,00 e no cartão de R$ 135,00',
            },
            {
                id: 1046,
                marca: 'Burberry',
                perfume: 'Touch',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Touch da marca Burberry, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1047,
                marca: 'Cartier',
                perfume: 'Declaration',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Declaration da marca Cartier, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1048,
                marca: 'Givenchy',
                perfume: 'Very Irresistible',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Very Irresistible da marca Givenchy, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1049,
                marca: 'Hugo Boss',
                perfume: 'Boss Bottled',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Boss Bottled da marca Hugo Boss, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1050,
                marca: 'Issey Miyake',
                perfume: 'L\'Eau d\'Issey Pour Homme',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume L\'Eau d\'Issey Pour Homme da marca Issey Miyake, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1051,
                marca: 'Jean Paul Gaultier',
                perfume: 'Classique',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Classique da marca Jean Paul Gaultier, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1052,
                marca: 'Kenzo',
                perfume: 'Kenzo Homme',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Kenzo Homme da marca Kenzo, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1053,
                marca: 'Lacoste',
                perfume: 'Lacoste Pour Femme',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 120,
                preco_cartao: 135,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Lacoste Pour Femme da marca Lacoste, tamanho 100, tipo EDT, genero Feminino, preço no pix de R$ 120,00 e no cartão de R$ 135,00',
            },
            {
                id: 1054,
                marca: 'Michael Kors',
                perfume: 'Sexy Amber',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 135,
                preco_cartao: 150,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Sexy Amber da marca Michael Kors, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 135,00 e no cartão de R$ 150,00',
            },
            {
                id: 1055,
                marca: 'Moschino',
                perfume: 'Fresh',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Fresh da marca Moschino, tamanho 100, tipo EDT, genero Feminino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1056,
                marca: 'Nina Ricci',
                perfume: 'Nina',
                tamanho: 80,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Nina da marca Nina Ricci, tamanho 80, tipo EDT, genero Feminino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1057,
                marca: 'Paco Rabanne',
                perfume: 'Invictus',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 135,
                preco_cartao: 150,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Invictus da marca Paco Rabanne, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 135,00 e no cartão de R$ 150,00',
            },
            {
                id: 1058,
                marca: 'Roberto Cavalli',
                perfume: 'Just Cavalli',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Just Cavalli da marca Roberto Cavalli, tamanho 100, tipo EDT, genero Feminino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1059,
                marca: 'Salvatore Ferragamo',
                perfume: 'F by Ferragamo',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 120,
                preco_cartao: 135,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume F by Ferragamo da marca Salvatore Ferragamo, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 120,00 e no cartão de R$ 135,00',
            },
            {
                id: 1060,
                marca: 'Tommy Hilfiger',
                perfume: 'Tommy Girl',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 115,
                preco_cartao: 130,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Tommy Girl da marca Tommy Hilfiger, tamanho 100, tipo EDT, genero Feminino, preço no pix de R$ 115,00 e no cartão de R$ 130,00',
            },
            {
                id: 1061,
                marca: 'Versace',
                perfume: 'Crystal Noir',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Crystal Noir da marca Versace, tamanho 90, tipo EDP, genero Feminino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1062,
                marca: 'Yves Saint Laurent',
                perfume: 'Y',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Masculino',
                preco_pix: 155,
                preco_cartao: 170,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Y da marca Yves Saint Laurent, tamanho 100, tipo EDP, genero Masculino, preço no pix de R$ 155,00 e no cartão de R$ 170,00',
            },
            {
                id: 1063,
                marca: 'Zara',
                perfume: 'Black Amber',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 90,
                preco_cartao: 105,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Black Amber da marca Zara, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 90,00 e no cartão de R$ 105,00',
            },
            {
                id: 1064,
                marca: 'Armani',
                perfume: 'Code',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 135,
                preco_cartao: 150,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Code da marca Armani, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 135,00 e no cartão de R$ 150,00',
            },
            {
                id: 1065,
                marca: 'Bvlgari',
                perfume: 'Omnia Crystalline',
                tamanho: 65,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Omnia Crystalline da marca Bvlgari, tamanho 65, tipo EDT, genero Feminino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1066,
                marca: 'Calvin Klein',
                perfume: 'CK One',
                tamanho: 200,
                tipo: 'EDT',
                genero: 'Unissex',
                preco_pix: 115,
                preco_cartao: 130,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume CK One da marca Calvin Klein, tamanho 200, tipo EDT, genero Unissex, preço no pix de R$ 115,00 e no cartão de R$ 130,00',
            },
            {
                id: 1067,
                marca: 'Dior',
                perfume: 'Miss Dior',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 160,
                preco_cartao: 175,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Miss Dior da marca Dior, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 160,00 e no cartão de R$ 175,00',
            },
            {
                id: 1068,
                marca: 'Dolce & Gabbana',
                perfume: 'The One',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Masculino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume The One da marca Dolce & Gabbana, tamanho 100, tipo EDP, genero Masculino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1069,
                marca: 'Gucci',
                perfume: 'Bloom',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 155,
                preco_cartao: 170,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Bloom da marca Gucci, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 155,00 e no cartão de R$ 170,00',
            },
            {
                id: 1070,
                marca: 'Hermès',
                perfume: 'Un Jardin Sur Le Nil',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Unissex',
                preco_pix: 150,
                preco_cartao: 165,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Un Jardin Sur Le Nil da marca Hermès, tamanho 100, tipo EDT, genero Unissex, preço no pix de R$ 150,00 e no cartão de R$ 165,00',
            },
            {
                id: 1071,
                marca: 'Jimmy Choo',
                perfume: 'Flash',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Flash da marca Jimmy Choo, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1072,
                marca: 'Lancôme',
                perfume: 'Trésor',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Trésor da marca Lancôme, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1073,
                marca: 'Marc Jacobs',
                perfume: 'Decadence',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 150,
                preco_cartao: 165,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Decadence da marca Marc Jacobs, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 150,00 e no cartão de R$ 165,00',
            },
            {
                id: 1074,
                marca: 'Montblanc',
                perfume: 'Emblem',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Emblem da marca Montblanc, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1075,
                marca: 'Narciso Rodriguez',
                perfume: 'Pure Musc',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 155,
                preco_cartao: 170,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Pure Musc da marca Narciso Rodriguez, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 155,00 e no cartão de R$ 170,00',
            },
            {
                id: 1076,
                marca: 'Prada',
                perfume: 'Candy',
                tamanho: 80,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Candy da marca Prada, tamanho 80, tipo EDP, genero Feminino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1077,
                marca: 'Ralph Lauren',
                perfume: 'Romance',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 135,
                preco_cartao: 150,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Romance da marca Ralph Lauren, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 135,00 e no cartão de R$ 150,00',
            },
            {
                id: 1078,
                marca: 'Thierry Mugler',
                perfume: 'Angel',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 160,
                preco_cartao: 175,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Angel da marca Thierry Mugler, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 160,00 e no cartão de R$ 175,00',
            },
            {
                id: 1079,
                marca: 'Tom Ford',
                perfume: 'Tobacco Vanille',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Unissex',
                preco_pix: 165,
                preco_cartao: 180,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Tobacco Vanille da marca Tom Ford, tamanho 100, tipo EDP, genero Unissex, preço no pix de R$ 165,00 e no cartão de R$ 180,00',
            },
            {
                id: 1080,
                marca: 'Valentino',
                perfume: 'Donna',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 150,
                preco_cartao: 165,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Donna da marca Valentino, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 150,00 e no cartão de R$ 165,00',
            },
            {
                id: 1081,
                marca: 'Viktor & Rolf',
                perfume: 'Spicebomb',
                tamanho: 90,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Spicebomb da marca Viktor & Rolf, tamanho 90, tipo EDT, genero Masculino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1082,
                marca: 'Yves Saint Laurent',
                perfume: 'Mon Paris',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 155,
                preco_cartao: 170,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Mon Paris da marca Yves Saint Laurent, tamanho 90, tipo EDP, genero Feminino, preço no pix de R$ 155,00 e no cartão de R$ 170,00',
            },
            {
                id: 1083,
                marca: 'Zadig & Voltaire',
                perfume: 'This Is Him',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume This Is Him da marca Zadig & Voltaire, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1084,
                marca: 'Armani',
                perfume: 'Sì',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 150,
                preco_cartao: 165,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Sì da marca Armani, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 150,00 e no cartão de R$ 165,00',
            },
            {
                id: 1085,
                marca: 'Bvlgari',
                perfume: 'Aqva',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 135,
                preco_cartao: 150,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Aqva da marca Bvlgari, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 135,00 e no cartão de R$ 150,00',
            },
            {
                id: 1086,
                marca: 'Calvin Klein',
                perfume: 'Euphoria',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 125,
                preco_cartao: 140,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Euphoria da marca Calvin Klein, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 125,00 e no cartão de R$ 140,00',
            },
            {
                id: 1087,
                marca: 'Dior',
                perfume: 'Fahrenheit',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 155,
                preco_cartao: 170,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Fahrenheit da marca Dior, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 155,00 e no cartão de R$ 170,00',
            },
            {
                id: 1088,
                marca: 'Dolce & Gabbana',
                perfume: 'K',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume K da marca Dolce & Gabbana, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1089,
                marca: 'Gucci',
                perfume: 'Flora',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Feminino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Flora da marca Gucci, tamanho 100, tipo EDT, genero Feminino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1090,
                marca: 'Hermès',
                perfume: 'Twilly',
                tamanho: 85,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 160,
                preco_cartao: 175,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Twilly da marca Hermès, tamanho 85, tipo EDP, genero Feminino, preço no pix de R$ 160,00 e no cartão de R$ 175,00',
            },
            {
                id: 1091,
                marca: 'Jimmy Choo',
                perfume: 'Fever',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Fever da marca Jimmy Choo, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1092,
                marca: 'Lancôme',
                perfume: 'Idôle',
                tamanho: 75,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 150,
                preco_cartao: 165,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Idôle da marca Lancôme, tamanho 75, tipo EDP, genero Feminino, preço no pix de R$ 150,00 e no cartão de R$ 165,00',
            },
            {
                id: 1093,
                marca: 'Marc Jacobs',
                perfume: 'Perfect',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Perfect da marca Marc Jacobs, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1094,
                marca: 'Montblanc',
                perfume: 'Explorer',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Masculino',
                preco_pix: 130,
                preco_cartao: 145,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Explorer da marca Montblanc, tamanho 100, tipo EDP, genero Masculino, preço no pix de R$ 130,00 e no cartão de R$ 145,00',
            },
            {
                id: 1095,
                marca: 'Narciso Rodriguez',
                perfume: 'Narciso Rouge',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 155,
                preco_cartao: 170,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Narciso Rouge da marca Narciso Rodriguez, tamanho 90, tipo EDP, genero Feminino, preço no pix de R$ 155,00 e no cartão de R$ 170,00',
            },
            {
                id: 1096,
                marca: 'Prada',
                perfume: 'Luna Rossa',
                tamanho: 100,
                tipo: 'EDT',
                genero: 'Masculino',
                preco_pix: 145,
                preco_cartao: 160,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Luna Rossa da marca Prada, tamanho 100, tipo EDT, genero Masculino, preço no pix de R$ 145,00 e no cartão de R$ 160,00',
            },
            {
                id: 1097,
                marca: 'Ralph Lauren',
                perfume: 'Woman',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 140,
                preco_cartao: 155,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Woman da marca Ralph Lauren, tamanho 100, tipo EDP, genero Feminino, preço no pix de R$ 140,00 e no cartão de R$ 155,00',
            },
            {
                id: 1098,
                marca: 'Thierry Mugler',
                perfume: 'Aura',
                tamanho: 90,
                tipo: 'EDP',
                genero: 'Feminino',
                preco_pix: 160,
                preco_cartao: 175,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Aura da marca Thierry Mugler, tamanho 90, tipo EDP, genero Feminino, preço no pix de R$ 160,00 e no cartão de R$ 175,00',
            },
            {
                id: 1099,
                marca: 'Tom Ford',
                perfume: 'Oud Wood',
                tamanho: 100,
                tipo: 'EDP',
                genero: 'Unissex',
                preco_pix: 170,
                preco_cartao: 185,
                link_compra: 'https://wa.me/whatsappphonenumber?text=Olá, gostaria de comprar o perfume Oud Wood da marca Tom Ford, tamanho 100, tipo EDP, genero Unissex, preço no pix de R$ 170,00 e no cartão de R$ 185,00',
            },
        ];
    },

    getPerfumesSmall() {
        return Promise.resolve(this.getData().slice(0, 10));
    },

    getPerfumesMedium() {
        return Promise.resolve(this.getData().slice(0, 50));
    },

    getPerfumesLarge() {
        return Promise.resolve(this.getData().slice(0, 200));
    },

    getPerfumesXLarge() {
        return Promise.resolve(this.getData());
    },

    getPerfumes(params: any) {
        const queryParams = params
            ? Object.keys(params)
                  .map((k) => encodeURIComponent(k) + '=' + encodeURIComponent(params[k]))
                  .join('&')
            : '';

        return fetch('https://www.primefaces.org/data/customers?' + queryParams).then((res) => res.json());
    }
};
