name: Deploy my personal website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Ensure this matches the version your project uses

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to DigitalOcean
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          curl -X POST "https://api.digitalocean.com/v2/apps/$APP_ID/deployments" \
          -H "Authorization: Bearer $DIGITALOCEAN_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"force_build": true}'
